# Project information
site_name: Smartcube Documentation
site_url: https://flokain.github.io/Smart-Cube/
site_author: Martin Donath
theme:
  name: material

# Repository
repo_name: https://github.com/flokain/Smart-Cube
repo_url: https://github.com/flokain/Smart-Cube
edit_uri: "github smartcube"
