# coding: utf-8

"""
    Smartcube API

    This APIis used to read and configure webhooks to be triggered by the sides of the cube  # noqa: E501

    OpenAPI spec version: v1
    Contact: flokain11@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Handler(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request': 'HttpRequest',
        'expected_response': 'int'
    }

    attribute_map = {
        'request': 'request',
        'expected_response': 'expectedResponse'
    }

    def __init__(self, request=None, expected_response=200):  # noqa: E501
        """Handler - a model defined in Swagger"""  # noqa: E501
        self._request = None
        self._expected_response = None
        self.discriminator = None
        self.request = request
        if expected_response is not None:
            self.expected_response = expected_response

    @property
    def request(self):
        """Gets the request of this Handler.  # noqa: E501


        :return: The request of this Handler.  # noqa: E501
        :rtype: HttpRequest
        """
        return self._request

    @request.setter
    def request(self, request):
        """Sets the request of this Handler.


        :param request: The request of this Handler.  # noqa: E501
        :type: HttpRequest
        """
        if request is None:
            raise ValueError("Invalid value for `request`, must not be `None`")  # noqa: E501

        self._request = request

    @property
    def expected_response(self):
        """Gets the expected_response of this Handler.  # noqa: E501


        :return: The expected_response of this Handler.  # noqa: E501
        :rtype: int
        """
        return self._expected_response

    @expected_response.setter
    def expected_response(self, expected_response):
        """Sets the expected_response of this Handler.


        :param expected_response: The expected_response of this Handler.  # noqa: E501
        :type: int
        """

        self._expected_response = expected_response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Handler, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Handler):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
