# coding: utf-8

"""
    Smartcube API

    This APIis used to read and configure webhooks to be triggered by the sides of the cube  # noqa: E501

    OpenAPI spec version: v1
    Contact: flokain11@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.system_config import SystemConfig  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemConfig(unittest.TestCase):
    """SystemConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemConfig(self):
        """Test SystemConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.system_config.SystemConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
