# coding: utf-8

"""
    Smartcube API

    This APIis used to read and configure webhooks to be triggered by the sides of the cube  # noqa: E501

    OpenAPI spec version: v1
    Contact: flokain11@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.state_api import StateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStateApi(unittest.TestCase):
    """StateApi unit test stubs"""

    def setUp(self):
        self.api = StateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_state_side_get(self):
        """Test case for state_side_get

        get the current CubeState  # noqa: E501
        """
        pass

    def test_state_system_get(self):
        """Test case for state_system_get

        get the current SystemState  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
