# coding: utf-8

"""
    Smartcube API

    This APIis used to read and configure webhooks to be triggered by the sides of the cube  # noqa: E501

    OpenAPI spec version: v1
    Contact: flokain11@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_api import SystemApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_system_config_get(self):
        """Test case for system_config_get

        get the configuration  # noqa: E501
        """
        pass

    def test_system_config_post(self):
        """Test case for system_config_post

        set the configuration  # noqa: E501
        """
        pass

    def test_system_reboot_post(self):
        """Test case for system_reboot_post

        reboots the System  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
