# coding: utf-8
from smartcube.models.base_model_ import Model
from smartcube import util
from ujson import loads


class HttpRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uri: str = None, method: str = 'GET', headers=None, payload: str = None):  # noqa: E501
        """HttpRequest - a model defined in Swagger

        :param uri: The uri of this HttpRequest.  # noqa: E501
        :type uri: str
        :param method: The method of this HttpRequest.  # noqa: E501
        :type method: str
        :param headers: The headers of this HttpRequest.  # noqa: E501
        :type headers: Dict[str, str]
        :param payload: The payload of this HttpRequest.  # noqa: E501
        :type payload: str
        """
        self.swagger_types = {
            'uri': str,
            'method': str,
            'headers': dict,
            'payload': str
        }

        self.attribute_map = {
            'uri': 'uri',
            'method': 'method',
            'headers': 'headers',
            'payload': 'payload'
        }
        self._uri = uri
        self._method = method
        self._headers = headers
        self._payload = payload

    @classmethod
    def from_dict(cls, dikt) -> 'HttpRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The httpRequest of this HttpRequest.  # noqa: E501
        :rtype: HttpRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uri(self) -> str:
        """Gets the uri of this HttpRequest.


        :return: The uri of this HttpRequest.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri: str):
        """Sets the uri of this HttpRequest.


        :param uri: The uri of this HttpRequest.
        :type uri: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    @property
    def method(self) -> str:
        """Gets the method of this HttpRequest.


        :return: The method of this HttpRequest.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this HttpRequest.


        :param method: The method of this HttpRequest.
        :type method: str
        """
        allowed_values = ["GET", "POST", "PUT", "DELETE", "HEAD", "PATCH", "OPTIONS"]  # noqa: E501
        if method not in allowed_values:
            raise ValueError(
                "Invalid value for `method` ({0}), must be one of {1}"
                .format(method, allowed_values)
            )

        self._method = method

    @property
    def headers(self):
        """Gets the headers of this HttpRequest.


        :return: The headers of this HttpRequest.
        :rtype: Dict[str, str]
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this HttpRequest.


        :param headers: The headers of this HttpRequest.
        :type headers: Dict[str, str]
        """

        self._headers = headers

    @property
    def payload(self) -> str:
        """Gets the payload of this HttpRequest.


        :return: The payload of this HttpRequest.
        :rtype: str
        """
        return self._payload

    @payload.setter
    def payload(self, payload: str):
        """Sets the payload of this HttpRequest.


        :param payload: The payload of this HttpRequest.
        :type payload: str
        """

        self._payload = payload

    @property
    def json(self) -> dict:
        """Gets the payload as json dict

        Returns:
            dict: The payload of this HttpRequest as dict
        """
        return loads(self._payload)

    def _render(self, string, **kwargs):
        import ure as re
        for key, value in kwargs:
            pattern = "{{{{{}}}}}".format(key)
            string = re.sub(pattern, value, string)
        return string

    def render(self, **kwargs):
        return HttpRequest(
            uri=self._render(self._uri, kwargs),
            method=self._render(self._method, kwargs),
            headers=[self._render(h, kwargs) for h in self._headers],
            payload=self._render(self._payload, kwargs)
        )
