from smartcube.models.base_model_ import Model
from smartcube import util


class Wifi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ssid: str = None, password: str = None):  # noqa: E501
        """Wifi - a model defined in Swagger

        :param ssid: The ssid of this Wifi.  # noqa: E501
        :type ssid: str
        :param password: The password of this Wifi.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'ssid': str,
            'password': str
        }

        self.attribute_map = {
            'ssid': 'ssid',
            'password': 'password'
        }
        self._ssid = ssid
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Wifi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Wifi of this Wifi.  # noqa: E501
        :rtype: Wifi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ssid(self) -> str:
        """Gets the ssid of this Wifi.

        the SSID of the Wifi to connect to  # noqa: E501

        :return: The ssid of this Wifi.
        :rtype: str
        """
        return self._ssid

    @ssid.setter
    def ssid(self, ssid: str):
        """Sets the ssid of this Wifi.

        the SSID of the Wifi to connect to  # noqa: E501

        :param ssid: The ssid of this Wifi.
        :type ssid: str
        """

        self._ssid = ssid

    @property
    def password(self) -> str:
        """Gets the password of this Wifi.

        the password of the wifi  # noqa: E501

        :return: The password of this Wifi.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Wifi.

        the password of the wifi  # noqa: E501

        :param password: The password of this Wifi.
        :type password: str
        """

        self._password = password

    # @classmethod
    # def get_all(cls):
    #     with open("/networks.json", "r") as f:
    #         wifi_dict = json.loads(f.read())
    #         wifi_dict = wifi_dict["known_networks"]
    #     return [cls.from_dict(w) for w in wifi_dict]

    # @classmethod
    # def save_all(cls,wifis):
    #     with open("/networks.json", "rw") as f:
    #         networks = json.loads(f.read())
    #         networks["known_networks"] = [JSONEncodeModel(wifi) for wifi in wifis]
    #         f.write(json.dumps(networks, indent=4))

    # def save(self):
    #     wifis = self.get_all()
    #     for wifi in wifis:
    #         if wifi.ssid == self.ssid:
    #             wifi.password = self.password
    #             self.save_all(wifis)
    #             return

    #     wifis.append(self)
    #     self.save_all(wifis)
