# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.side_id import SideId  # noqa: F401,E501
from swagger_server import util


class CubeState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, side_id: SideId=None, last_change: datetime=None):  # noqa: E501
        """CubeState - a model defined in Swagger

        :param side_id: The side_id of this CubeState.  # noqa: E501
        :type side_id: SideId
        :param last_change: The last_change of this CubeState.  # noqa: E501
        :type last_change: datetime
        """
        self.swagger_types = {
            'side_id': SideId,
            'last_change': datetime
        }

        self.attribute_map = {
            'side_id': 'sideId',
            'last_change': 'lastChange'
        }
        self._side_id = side_id
        self._last_change = last_change

    @classmethod
    def from_dict(cls, dikt) -> 'CubeState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CubeState of this CubeState.  # noqa: E501
        :rtype: CubeState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def side_id(self) -> SideId:
        """Gets the side_id of this CubeState.


        :return: The side_id of this CubeState.
        :rtype: SideId
        """
        return self._side_id

    @side_id.setter
    def side_id(self, side_id: SideId):
        """Sets the side_id of this CubeState.


        :param side_id: The side_id of this CubeState.
        :type side_id: SideId
        """

        self._side_id = side_id

    @property
    def last_change(self) -> datetime:
        """Gets the last_change of this CubeState.


        :return: The last_change of this CubeState.
        :rtype: datetime
        """
        return self._last_change

    @last_change.setter
    def last_change(self, last_change: datetime):
        """Sets the last_change of this CubeState.


        :param last_change: The last_change of this CubeState.
        :type last_change: datetime
        """

        self._last_change = last_change
