# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SystemState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time_remaining: int=None, time_passed: int=None):  # noqa: E501
        """SystemState - a model defined in Swagger

        :param time_remaining: The time_remaining of this SystemState.  # noqa: E501
        :type time_remaining: int
        :param time_passed: The time_passed of this SystemState.  # noqa: E501
        :type time_passed: int
        """
        self.swagger_types = {
            'time_remaining': int,
            'time_passed': int
        }

        self.attribute_map = {
            'time_remaining': 'timeRemaining',
            'time_passed': 'timePassed'
        }
        self._time_remaining = time_remaining
        self._time_passed = time_passed

    @classmethod
    def from_dict(cls, dikt) -> 'SystemState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SystemState of this SystemState.  # noqa: E501
        :rtype: SystemState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_remaining(self) -> int:
        """Gets the time_remaining of this SystemState.

        estimated remaining time of operation in seconds. -1 means infintely  # noqa: E501

        :return: The time_remaining of this SystemState.
        :rtype: int
        """
        return self._time_remaining

    @time_remaining.setter
    def time_remaining(self, time_remaining: int):
        """Sets the time_remaining of this SystemState.

        estimated remaining time of operation in seconds. -1 means infintely  # noqa: E501

        :param time_remaining: The time_remaining of this SystemState.
        :type time_remaining: int
        """

        self._time_remaining = time_remaining

    @property
    def time_passed(self) -> int:
        """Gets the time_passed of this SystemState.

        time that has passed since device was switched on  # noqa: E501

        :return: The time_passed of this SystemState.
        :rtype: int
        """
        return self._time_passed

    @time_passed.setter
    def time_passed(self, time_passed: int):
        """Sets the time_passed of this SystemState.

        time that has passed since device was switched on  # noqa: E501

        :param time_passed: The time_passed of this SystemState.
        :type time_passed: int
        """

        self._time_passed = time_passed
